namespace CapstoneSharp.Arm;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "IdentifierTypo")]
public enum CapstoneArmSystemRegister : uint
{
    Invalid = 0,
    SPSR_C = 1,
    SPSR_X = 2,
    SPSR_S = 4,
    SPSR_F = 8,
    CPSR_C = 16,
    CPSR_X = 32,
    CPSR_S = 64,
    CPSR_F = 128,
    APSR = 256,
    APSR_G,
    APSR_NZCVQ,
    APSR_NZCVQG,
    IAPSR,
    IAPSR_G,
    IAPSR_NZCVQG,
    IAPSR_NZCVQ,
    EAPSR,
    EAPSR_G,
    EAPSR_NZCVQG,
    EAPSR_NZCVQ,
    XPSR,
    XPSR_G,
    XPSR_NZCVQG,
    XPSR_NZCVQ,
    IPSR,
    EPSR,
    IEPSR,
    MSP,
    PSP,
    PRIMASK,
    BASEPRI,
    BASEPRI_MAX,
    FAULTMASK,
    CONTROL,
    R8_USR,
    R9_USR,
    R10_USR,
    R11_USR,
    R12_USR,
    SP_USR,
    LR_USR,
    R8_FIQ,
    R9_FIQ,
    R10_FIQ,
    R11_FIQ,
    R12_FIQ,
    SP_FIQ,
    LR_FIQ,
    LR_IRQ,
    SP_IRQ,
    LR_SVC,
    SP_SVC,
    LR_ABT,
    SP_ABT,
    LR_UND,
    SP_UND,
    LR_MON,
    SP_MON,
    ELR_HYP,
    SP_HYP,
    SPSR_FIQ,
    SPSR_IRQ,
    SPSR_SVC,
    SPSR_ABT,
    SPSR_UND,
    SPSR_MON,
    SPSR_HYP,
}
